import type { NextPage } from "next";
import Head from "next/head";
import MainPage from "../components/MainPage/MainPage";
import styles from "../styles/Home.module.css";

import { useEffect, useState } from "react";

interface Props {
  time: number;
}

const Home: NextPage<Props> = (props) => {
  const [time, setTime] = useState<number>(Date.now());
  useEffect(() => {
    async function getTime() {
      try {
        const res = await fetch(`${process.env.APP_URL}/api/time`, {
          method: "GET",
        });
        const newTime = await res.json();
        setTime(newTime);
      } catch (err) {
        console.log(err);
      }
    }

    getTime();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Time Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/timecheck.svg" />
      </Head>
      <MainPage time={props.time} />
    </div>
  );
};

export default Home;
