import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import db from "../db";
import MainClock from "../components/MainClock/MainClock";
import Taskbar from "../components/Taskbar/Taskbar";
import { Grid } from "semantic-ui-react";
import FormModal from "../components/FormModal/FormModal";
import RetrieveTask from "../components/RetrieveTask/RetrieveTask";
import { TimeProvider } from "../components/TimeProvider/TimeProvider";
import { useEffect, useState } from "react";

interface Props {
  time: number;
}

const Home: NextPage<Props> = (props) => {
  const [time, setTime] = useState<number>(Date.now());
  useEffect(() => {
    async function getTime() {
      try {
        const res = await fetch("https://timecheck.vercel.app/api/time", {
          method: "GET",
        });
        const newTime = await res.json();
        setTime(newTime);
      } catch (err) {
        console.log(err);
      }
    }

    getTime();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Hello Everyone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TimeProvider time={time}>
        <Grid stackable divided columns={2} className={styles.main}>
          <Grid.Column width={12}>
            <MainClock time={time} />
          </Grid.Column>

          <Grid.Column width={4}>
            <Taskbar />
            <RetrieveTask />
            <FormModal />
          </Grid.Column>
        </Grid>
      </TimeProvider>
    </div>
  );
};

//Here, makes call to server to get the time, and insert that into props, which will be obtained by the context Time Provider.

// export async function getServerSideProps() {
//   const res = await fetch("http://timecheck.vercel.app/api/time", {
//     method: "GET",
//   });
//   const time = await res.json();

//   return {
//     props: {
//       time: time,
//     },
//   };
// }

export default Home;
